import React from "react";

    function SlideComponent2({title}:{title:string}){
        return(
            <div className="group-3">
              <div className="coin">
                <div className="element">
                  <img className="vector" alt="Vector" src="/img/vector.svg" />
                  <img className="vector-2" alt="Vector" src="/img/vector-1.svg" />
                  <img className="vector-3" alt="Vector" src="/img/vector-2.svg" />
                  <img className="vector-4" alt="Vector" src="/img/vector-3.svg" />
                  <img className="vector-5" alt="Vector" src="/img/vector-4.svg" />
                  <img className="vector-6" alt="Vector" src="/img/vector-5.svg" />
                  <img className="vector-7" alt="Vector" src="/img/vector-6.svg" />
                  <img className="vector-8" alt="Vector" src="/img/vector-7.svg" />
                  <img className="vector-9" alt="Vector" src="/img/vector-8.svg" />
                  <img className="vector-10" alt="Vector" src="/img/vector-9.svg" />
                  <img className="vector-11" alt="Vector" src="/img/vector-10.svg" />
                  <img className="vector-12" alt="Vector" src="/img/vector-11.svg" />
                  <img className="vector-13" alt="Vector" src="/img/vector-12.svg" />
                  <img className="vector-14" alt="Vector" src="/img/vector-13.svg" />
                  <img className="vector-15" alt="Vector" src="/img/vector-14.svg" />
                  <img className="vector-16" alt="Vector" src="/img/vector-15.svg" />
                  <img className="vector-17" alt="Vector" src="/img/vector-16.svg" />
                  <img className="vector-18" alt="Vector" src="/img/vector-17.svg" />
                  <img className="vector-19" alt="Vector" src="/img/vector-18.svg" />
                  <img className="vector-20" alt="Vector" src="/img/vector-19.svg" />
                  <img className="vector-21" alt="Vector" src="/img/vector-20.svg" />
                  <img className="vector-22" alt="Vector" src="/img/vector-21.svg" />
                  <img className="vector-23" alt="Vector" src="/img/vector-22.svg" />
                  <img className="vector-24" alt="Vector" src="/img/vector-23.svg" />
                  <img className="vector-25" alt="Vector" src="/img/vector-24.svg" />
                  <img className="vector-26" alt="Vector" src="/img/vector-25.svg" />
                  <img className="vector-27" alt="Vector" src="/img/vector-26.svg" />
                  <img className="vector-28" alt="Vector" src="/img/vector-27.svg" />
                  <img className="vector-29" alt="Vector" src="/img/vector-28.svg" />
                  <img className="vector-30" alt="Vector" src="/img/vector-29.svg" />
                  <img className="vector-31" alt="Vector" src="/img/vector-30.svg" />
                  <img className="vector-32" alt="Vector" src="/img/vector-31.svg" />
                  <img className="vector-33" alt="Vector" src="/img/vector-32.svg" />
                  <img className="vector-34" alt="Vector" src="/img/vector-33.svg" />
                  <img className="vector-35" alt="Vector" src="/img/vector-34.svg" />
                  <img className="vector-36" alt="Vector" src="/img/vector-35.svg" />
                  <img className="vector-37" alt="Vector" src="/img/vector-36.svg" />
                  <img className="vector-38" alt="Vector" src="/img/vector-37.svg" />
                  <img className="vector-39" alt="Vector" src="/img/vector-38.svg" />
                  <img className="vector-40" alt="Vector" src="/img/vector-39.svg" />
                  <img className="vector-41" alt="Vector" src="/img/vector-40.svg" />
                  <img className="vector-42" alt="Vector" src="/img/vector-41.svg" />
                  <img className="vector-43" alt="Vector" src="/img/vector-42.svg" />
                  <img className="vector-44" alt="Vector" src="/img/vector-584.png" />
                  <img className="vector-45" alt="Vector" src="/img/vector-44.svg" />
                  <img className="vector-46" alt="Vector" src="/img/vector-584.png" />
                  <img className="vector-47" alt="Vector" src="/img/vector-46.svg" />
                  <img className="vector-48" alt="Vector" src="/img/vector-47.svg" />
                  <img className="vector-49" alt="Vector" src="/img/vector-48.svg" />
                  <img className="vector-50" alt="Vector" src="/img/vector-49.svg" />
                  <img className="vector-51" alt="Vector" src="/img/vector-50.svg" />
                  <img className="vector-52" alt="Vector" src="/img/vector-51.svg" />
                  <img className="vector-53" alt="Vector" src="/img/vector-52.svg" />
                  <img className="vector-54" alt="Vector" src="/img/vector-53.svg" />
                  <img className="vector-55" alt="Vector" src="/img/vector-54.svg" />
                  <img className="vector-56" alt="Vector" src="/img/vector-55.svg" />
                  <img className="vector-57" alt="Vector" src="/img/vector-56.svg" />
                  <img className="vector-58" alt="Vector" src="/img/vector-57.svg" />
                  <img className="vector-59" alt="Vector" src="/img/vector-58.svg" />
                  <img className="vector-60" alt="Vector" src="/img/vector-59.svg" />
                  <img className="vector-61" alt="Vector" src="/img/vector-60.svg" />
                  <img className="vector-62" alt="Vector" src="/img/vector-61.svg" />
                  <img className="vector-63" alt="Vector" src="/img/vector-62.svg" />
                  <img className="vector-64" alt="Vector" src="/img/vector-63.svg" />
                  <img className="vector-65" alt="Vector" src="/img/vector-64.svg" />
                  <img className="vector-66" alt="Vector" src="/img/vector-65.svg" />
                  <img className="vector-67" alt="Vector" src="/img/vector-66.svg" />
                  <img className="vector-68" alt="Vector" src="/img/vector-67.svg" />
                  <img className="vector-69" alt="Vector" src="/img/vector-68.svg" />
                  <img className="vector-70" alt="Vector" src="/img/vector-69.svg" />
                  <img className="vector-71" alt="Vector" src="/img/vector-70.svg" />
                  <img className="vector-72" alt="Vector" src="/img/vector-71.svg" />
                  <img className="vector-73" alt="Vector" src="/img/vector-72.svg" />
                  <img className="vector-74" alt="Vector" src="/img/vector-73.svg" />
                  <img className="vector-75" alt="Vector" src="/img/vector-584.png" />
                  <img className="vector-76" alt="Vector" src="/img/vector-75.svg" />
                  <img className="vector-77" alt="Vector" src="/img/vector-76.svg" />
                  <img className="vector-78" alt="Vector" src="/img/vector-77.svg" />
                  <img className="vector-79" alt="Vector" src="/img/vector-78.svg" />
                  <img className="vector-80" alt="Vector" src="/img/vector-79.svg" />
                  <img className="vector-81" alt="Vector" src="/img/vector-80.svg" />
                  <img className="vector-82" alt="Vector" src="/img/vector-81.svg" />
                  <img className="vector-83" alt="Vector" src="/img/vector-82.svg" />
                  <img className="vector-84" alt="Vector" src="/img/vector-83.svg" />
                  <img className="vector-85" alt="Vector" src="/img/vector-84.svg" />
                  <img className="vector-86" alt="Vector" src="/img/vector-85.svg" />
                  <img className="vector-87" alt="Vector" src="/img/vector-86.svg" />
                  <img className="vector-88" alt="Vector" src="/img/vector-87.svg" />
                  <img className="vector-89" alt="Vector" src="/img/vector-88.svg" />
                  <img className="vector-90" alt="Vector" src="/img/vector-89.svg" />
                  <img className="vector-91" alt="Vector" src="/img/vector-90.svg" />
                  <img className="vector-92" alt="Vector" src="/img/vector-91.svg" />
                  <img className="vector-91" alt="Vector" src="/img/vector-92.svg" />
                  <img className="vector-93" alt="Vector" src="/img/vector-93.svg" />
                  <img className="vector-94" alt="Vector" src="/img/vector-94.svg" />
                  <img className="vector-95" alt="Vector" src="/img/vector-95.svg" />
                  <img className="vector-96" alt="Vector" src="/img/vector-96.svg" />
                  <img className="vector-97" alt="Vector" src="/img/vector-97.svg" />
                  <img className="vector-98" alt="Vector" src="/img/vector-98.svg" />
                  <img className="vector-99" alt="Vector" src="/img/vector-99.svg" />
                  <img className="vector-100" alt="Vector" src="/img/vector-100.svg" />
                  <img className="vector-101" alt="Vector" src="/img/vector-101.svg" />
                  <img className="vector-102" alt="Vector" src="/img/vector-102.svg" />
                  <img className="vector-103" alt="Vector" src="/img/vector-103.svg" />
                  <img className="vector-104" alt="Vector" src="/img/vector-104.svg" />
                  <img className="vector-105" alt="Vector" src="/img/vector-105.svg" />
                  <img className="vector-106" alt="Vector" src="/img/vector-106.svg" />
                  <img className="vector-107" alt="Vector" src="/img/vector-107.svg" />
                  <img className="vector-108" alt="Vector" src="/img/vector-108.svg" />
                  <img className="vector-109" alt="Vector" src="/img/vector-109.svg" />
                  <img className="vector-110" alt="Vector" src="/img/vector-110.svg" />
                  <img className="vector-111" alt="Vector" src="/img/vector-111.svg" />
                  <img className="vector-112" alt="Vector" src="/img/vector-584.png" />
                  <img className="vector-113" alt="Vector" src="/img/vector-113.svg" />
                  <img className="vector-114" alt="Vector" src="/img/vector-114.svg" />
                  <img className="vector-115" alt="Vector" src="/img/vector-115.svg" />
                  <img className="vector-116" alt="Vector" src="/img/vector-116.svg" />
                  <img className="vector-117" alt="Vector" src="/img/vector-117.svg" />
                  <img className="vector-118" alt="Vector" src="/img/vector-118.svg" />
                  <img className="vector-119" alt="Vector" src="/img/vector-119.svg" />
                  <img className="vector-120" alt="Vector" src="/img/vector-120.svg" />
                  <img className="vector-121" alt="Vector" src="/img/vector-121.svg" />
                  <img className="vector-122" alt="Vector" src="/img/vector-122.svg" />
                  <img className="vector-123" alt="Vector" src="/img/vector-123.svg" />
                  <img className="vector-124" alt="Vector" src="/img/vector-124.svg" />
                  <img className="vector-125" alt="Vector" src="/img/vector-125.svg" />
                  <img className="vector-126" alt="Vector" src="/img/vector-126.svg" />
                  <img className="vector-127" alt="Vector" src="/img/vector-127.svg" />
                  <img className="vector-128" alt="Vector" src="/img/vector-128.svg" />
                  <img className="vector-129" alt="Vector" src="/img/vector-129.svg" />
                  <img className="vector-130" alt="Vector" src="/img/vector-130.svg" />
                  <img className="vector-131" alt="Vector" src="/img/vector-131.svg" />
                  <img className="vector-132" alt="Vector" src="/img/vector-132.svg" />
                  <img className="vector-133" alt="Vector" src="/img/vector-133.svg" />
                  <img className="vector-134" alt="Vector" src="/img/vector-134.svg" />
                  <img className="vector-135" alt="Vector" src="/img/vector-135.svg" />
                  <img className="vector-136" alt="Vector" src="/img/vector-136.svg" />
                  <img className="vector-137" alt="Vector" src="/img/vector-137.svg" />
                  <img className="vector-138" alt="Vector" src="/img/vector-138.svg" />
                  <img className="vector-139" alt="Vector" src="/img/vector-139.svg" />
                  <img className="vector-140" alt="Vector" src="/img/vector-140.svg" />
                  <img className="vector-141" alt="Vector" src="/img/vector-141.svg" />
                  <img className="vector-142" alt="Vector" src="/img/vector-142.svg" />
                  <img className="vector-143" alt="Vector" src="/img/vector-143.svg" />
                  <img className="vector-144" alt="Vector" src="/img/vector-144.svg" />
                  <img className="vector-145" alt="Vector" src="/img/vector-145.svg" />
                  <img className="vector-146" alt="Vector" src="/img/vector-146.svg" />
                  <img className="vector-147" alt="Vector" src="/img/vector-147.svg" />
                  <img className="vector-148" alt="Vector" src="/img/vector-148.svg" />
                  <img className="vector-149" alt="Vector" src="/img/vector-149.svg" />
                  <img className="vector-150" alt="Vector" src="/img/vector-150.svg" />
                  <img className="vector-151" alt="Vector" src="/img/vector-151.svg" />
                  <img className="vector-152" alt="Vector" src="/img/vector-152.svg" />
                  <img className="vector-153" alt="Vector" src="/img/vector-153.svg" />
                  <img className="vector-154" alt="Vector" src="/img/vector-154.svg" />
                  <img className="vector-155" alt="Vector" src="/img/vector-155.svg" />
                  <img className="vector-156" alt="Vector" src="/img/vector-156.svg" />
                  <img className="vector-157" alt="Vector" src="/img/vector-157.svg" />
                  <img className="vector-158" alt="Vector" src="/img/vector-158.svg" />
                  <img className="vector-159" alt="Vector" src="/img/vector-159.svg" />
                  <img className="vector-160" alt="Vector" src="/img/vector-160.svg" />
                  <img className="vector-161" alt="Vector" src="/img/vector-161.svg" />
                  <img className="vector-162" alt="Vector" src="/img/vector-162.svg" />
                  <img className="vector-163" alt="Vector" src="/img/vector-163.svg" />
                  <img className="vector-164" alt="Vector" src="/img/vector-164.svg" />
                  <img className="vector-165" alt="Vector" src="/img/vector-165.svg" />
                  <img className="vector-166" alt="Vector" src="/img/vector-166.svg" />
                  <img className="vector-167" alt="Vector" src="/img/vector-167.svg" />
                  <img className="vector-168" alt="Vector" src="/img/vector-168.svg" />
                  <img className="vector-169" alt="Vector" src="/img/vector-169.svg" />
                  <img className="vector-170" alt="Vector" src="/img/vector-170.svg" />
                  <img className="vector-171" alt="Vector" src="/img/vector-171.svg" />
                  <img className="vector-172" alt="Vector" src="/img/vector-172.svg" />
                  <img className="vector-173" alt="Vector" src="/img/vector-173.svg" />
                  <img className="vector-174" alt="Vector" src="/img/vector-174.svg" />
                  <img className="vector-175" alt="Vector" src="/img/vector-175.svg" />
                  <img className="vector-176" alt="Vector" src="/img/vector-176.svg" />
                  <img className="vector-177" alt="Vector" src="/img/vector-177.svg" />
                  <img className="vector-178" alt="Vector" src="/img/vector-178.svg" />
                  <img className="vector-179" alt="Vector" src="/img/vector-179.svg" />
                  <img className="vector-180" alt="Vector" src="/img/vector-180.svg" />
                  <img className="vector-181" alt="Vector" src="/img/vector-181.svg" />
                  <img className="vector-182" alt="Vector" src="/img/vector-182.svg" />
                  <img className="vector-183" alt="Vector" src="/img/vector-183.svg" />
                  <img className="vector-184" alt="Vector" src="/img/vector-184.svg" />
                  <img className="vector-185" alt="Vector" src="/img/vector-185.svg" />
                  <img className="vector-186" alt="Vector" src="/img/vector-186.svg" />
                  <img className="vector-187" alt="Vector" src="/img/vector-187.svg" />
                  <img className="vector-188" alt="Vector" src="/img/vector-188.svg" />
                  <img className="vector-189" alt="Vector" src="/img/vector-189.svg" />
                  <img className="vector-190" alt="Vector" src="/img/vector-190.png" />
                  <img className="vector-191" alt="Vector" src="/img/vector-191.svg" />
                  <img className="vector-192" alt="Vector" src="/img/vector-192.svg" />
                  <img className="vector-193" alt="Vector" src="/img/vector-193.svg" />
                  <img className="vector-194" alt="Vector" src="/img/vector-194.svg" />
                  <img className="vector-195" alt="Vector" src="/img/vector-195.svg" />
                  <img className="vector-196" alt="Vector" src="/img/vector-196.svg" />
                  <img className="vector-197" alt="Vector" src="/img/vector-197.svg" />
                  <img className="vector-198" alt="Vector" src="/img/vector-198.svg" />
                  <img className="vector-199" alt="Vector" src="/img/vector-199.svg" />
                  <img className="vector-200" alt="Vector" src="/img/vector-200.svg" />
                  <img className="vector-201" alt="Vector" src="/img/vector-201.svg" />
                  <img className="vector-202" alt="Vector" src="/img/vector-202.svg" />
                  <img className="vector-203" alt="Vector" src="/img/vector-203.svg" />
                  <img className="vector-204" alt="Vector" src="/img/vector-204.svg" />
                  <img className="vector-205" alt="Vector" src="/img/vector-205.svg" />
                  <img className="vector-206" alt="Vector" src="/img/vector-206.svg" />
                  <img className="vector-207" alt="Vector" src="/img/vector-207.svg" />
                  <img className="vector-208" alt="Vector" src="/img/vector-208.svg" />
                  <img className="vector-209" alt="Vector" src="/img/vector-209.svg" />
                  <img className="vector-210" alt="Vector" src="/img/vector-210.svg" />
                  <img className="vector-211" alt="Vector" src="/img/vector-211.svg" />
                  <img className="vector-212" alt="Vector" src="/img/vector-212.svg" />
                  <img className="vector-213" alt="Vector" src="/img/vector-213.svg" />
                  <img className="vector-214" alt="Vector" src="/img/vector-214.svg" />
                  <img className="vector-215" alt="Vector" src="/img/vector-215.svg" />
                  <img className="vector-216" alt="Vector" src="/img/vector-216.svg" />
                  <img className="vector-217" alt="Vector" src="/img/vector-217.svg" />
                  <img className="vector-218" alt="Vector" src="/img/vector-218.svg" />
                  <img className="vector-219" alt="Vector" src="/img/vector-219.svg" />
                  <img className="vector-220" alt="Vector" src="/img/vector-220.svg" />
                  <img className="vector-221" alt="Vector" src="/img/vector-221.svg" />
                  <img className="vector-222" alt="Vector" src="/img/vector-222.svg" />
                  <img className="vector-223" alt="Vector" src="/img/vector-223.svg" />
                  <img className="vector-224" alt="Vector" src="/img/vector-224.svg" />
                  <img className="vector-225" alt="Vector" src="/img/vector-225.svg" />
                  <img className="vector-226" alt="Vector" src="/img/vector-226.svg" />
                  <img className="vector-227" alt="Vector" src="/img/vector-227.svg" />
                  <img className="vector-228" alt="Vector" src="/img/vector-228.svg" />
                  <img className="vector-229" alt="Vector" src="/img/vector-229.svg" />
                  <img className="vector-230" alt="Vector" src="/img/vector-230.svg" />
                  <img className="vector-231" alt="Vector" src="/img/vector-231.svg" />
                  <img className="vector-232" alt="Vector" src="/img/vector-232.svg" />
                  <img className="vector-233" alt="Vector" src="/img/vector-233.svg" />
                  <img className="vector-234" alt="Vector" src="/img/vector-234.svg" />
                  <img className="vector-235" alt="Vector" src="/img/vector-235.svg" />
                  <img className="vector-236" alt="Vector" src="/img/vector-236.svg" />
                  <img className="vector-237" alt="Vector" src="/img/vector-237.svg" />
                  <img className="vector-238" alt="Vector" src="/img/vector-238.svg" />
                  <img className="vector-239" alt="Vector" src="/img/vector-239.svg" />
                  <img className="vector-240" alt="Vector" src="/img/vector-240.svg" />
                  <img className="vector-241" alt="Vector" src="/img/vector-241.svg" />
                  <img className="vector-242" alt="Vector" src="/img/vector-242.svg" />
                  <img className="vector-243" alt="Vector" src="/img/vector-243.svg" />
                  <img className="vector-244" alt="Vector" src="/img/vector-244.svg" />
                  <img className="vector-245" alt="Vector" src="/img/vector-245.svg" />
                  <img className="vector-246" alt="Vector" src="/img/vector-246.svg" />
                  <img className="vector-247" alt="Vector" src="/img/vector-247.svg" />
                  <img className="vector-248" alt="Vector" src="/img/vector-248.svg" />
                  <img className="vector-249" alt="Vector" src="/img/vector-249.svg" />
                  <img className="vector-250" alt="Vector" src="/img/vector-250.svg" />
                  <img className="vector-251" alt="Vector" src="/img/vector-251.svg" />
                  <img className="vector-252" alt="Vector" src="/img/vector-252.svg" />
                  <img className="vector-253" alt="Vector" src="/img/vector-253.svg" />
                  <img className="vector-254" alt="Vector" src="/img/vector-254.svg" />
                  <img className="vector-255" alt="Vector" src="/img/vector-255.svg" />
                  <img className="vector-256" alt="Vector" src="/img/vector-256.svg" />
                  <img className="vector-257" alt="Vector" src="/img/vector-257.svg" />
                  <img className="vector-258" alt="Vector" src="/img/vector-258.svg" />
                  <img className="vector-259" alt="Vector" src="/img/vector-259.svg" />
                  <img className="vector-260" alt="Vector" src="/img/vector-260.svg" />
                  <img className="vector-261" alt="Vector" src="/img/vector-261.svg" />
                  <img className="vector-262" alt="Vector" src="/img/vector-262.svg" />
                  <img className="vector-263" alt="Vector" src="/img/vector-263.svg" />
                  <img className="vector-264" alt="Vector" src="/img/vector-264.svg" />
                  <img className="vector-265" alt="Vector" src="/img/vector-265.svg" />
                  <img className="vector-266" alt="Vector" src="/img/vector-266.svg" />
                  <img className="vector-267" alt="Vector" src="/img/vector-267.svg" />
                  <img className="vector-268" alt="Vector" src="/img/vector-268.svg" />
                  <img className="vector-269" alt="Vector" src="/img/vector-269.svg" />
                  <img className="vector-270" alt="Vector" src="/img/vector-270.svg" />
                  <img className="vector-271" alt="Vector" src="/img/vector-271.svg" />
                  <img className="vector-272" alt="Vector" src="/img/vector-272.svg" />
                  <img className="vector-273" alt="Vector" src="/img/vector-273.svg" />
                  <img className="vector-274" alt="Vector" src="/img/vector-274.svg" />
                  <img className="vector-275" alt="Vector" src="/img/vector-275.svg" />
                  <img className="vector-276" alt="Vector" src="/img/vector-276.svg" />
                  <img className="vector-277" alt="Vector" src="/img/vector-277.svg" />
                  <img className="vector-278" alt="Vector" src="/img/vector-278.svg" />
                  <img className="vector-279" alt="Vector" src="/img/vector-279.svg" />
                  <img className="vector-280" alt="Vector" src="/img/vector-280.svg" />
                  <img className="vector-281" alt="Vector" src="/img/vector-281.svg" />
                  <img className="vector-282" alt="Vector" src="/img/vector-282.svg" />
                  <img className="vector-283" alt="Vector" src="/img/vector-283.svg" />
                  <img className="vector-284" alt="Vector" src="/img/vector-284.svg" />
                  <img className="vector-285" alt="Vector" src="/img/vector-285.svg" />
                  <img className="vector-286" alt="Vector" src="/img/vector-286.svg" />
                  <img className="vector-287" alt="Vector" src="/img/vector-287.svg" />
                  <img className="vector-288" alt="Vector" src="/img/vector-288.svg" />
                  <img className="vector-289" alt="Vector" src="/img/vector-289.svg" />
                  <img className="vector-290" alt="Vector" src="/img/vector-290.svg" />
                  <img className="vector-291" alt="Vector" src="/img/vector-291.svg" />
                  <img className="vector-292" alt="Vector" src="/img/vector-292.svg" />
                  <img className="vector-293" alt="Vector" src="/img/vector-293.svg" />
                  <img className="vector-294" alt="Vector" src="/img/vector-294.svg" />
                  <img className="vector-295" alt="Vector" src="/img/vector-295.svg" />
                  <img className="vector-296" alt="Vector" src="/img/vector-296.svg" />
                  <img className="vector-297" alt="Vector" src="/img/vector-297.svg" />
                  <img className="vector-298" alt="Vector" src="/img/vector-298.svg" />
                  <img className="vector-299" alt="Vector" src="/img/vector-299.svg" />
                  <img className="vector-300" alt="Vector" src="/img/vector-300.svg" />
                  <img className="vector-301" alt="Vector" src="/img/vector-301.svg" />
                  <img className="vector-302" alt="Vector" src="/img/vector-302.svg" />
                  <img className="vector-303" alt="Vector" src="/img/vector-303.svg" />
                  <img className="vector-304" alt="Vector" src="/img/vector-304.svg" />
                  <img className="vector-305" alt="Vector" src="/img/vector-305.svg" />
                  <img className="vector-306" alt="Vector" src="/img/vector-306.svg" />
                  <img className="vector-307" alt="Vector" src="/img/vector-307.svg" />
                  <img className="vector-308" alt="Vector" src="/img/vector-308.svg" />
                  <img className="vector-309" alt="Vector" src="/img/vector-309.svg" />
                  <img className="vector-310" alt="Vector" src="/img/vector-310.svg" />
                  <img className="vector-311" alt="Vector" src="/img/vector-311.svg" />
                  <img className="vector-312" alt="Vector" src="/img/vector-312.svg" />
                  <img className="vector-313" alt="Vector" src="/img/vector-313.svg" />
                  <img className="vector-314" alt="Vector" src="/img/vector-314.svg" />
                  <img className="vector-315" alt="Vector" src="/img/vector-315.svg" />
                  <img className="vector-316" alt="Vector" src="/img/vector-316.svg" />
                  <img className="vector-317" alt="Vector" src="/img/vector-317.svg" />
                  <img className="vector-318" alt="Vector" src="/img/vector-318.svg" />
                  <img className="vector-319" alt="Vector" src="/img/vector-319.svg" />
                  <img className="vector-87" alt="Vector" src="/img/vector-320.svg" />
                  <img className="vector-85" alt="Vector" src="/img/vector-321.svg" />
                  <img className="vector-320" alt="Vector" src="/img/vector-322.svg" />
                  <img className="vector-89" alt="Vector" src="/img/vector-323.svg" />
                  <img className="vector-321" alt="Vector" src="/img/vector-324.svg" />
                  <img className="vector-322" alt="Vector" src="/img/vector-325.svg" />
                  <img className="vector-94" alt="Vector" src="/img/vector-326.svg" />
                  <img className="vector-323" alt="Vector" src="/img/vector-327.svg" />
                  <img className="vector-324" alt="Vector" src="/img/vector-328.svg" />
                  <img className="vector-325" alt="Vector" src="/img/vector-329.svg" />
                  <img className="vector-326" alt="Vector" src="/img/vector-330.svg" />
                  <img className="vector-327" alt="Vector" src="/img/vector-331.svg" />
                  <img className="vector-328" alt="Vector" src="/img/vector-332.svg" />
                  <img className="vector-329" alt="Vector" src="/img/vector-333.svg" />
                  <img className="vector-330" alt="Vector" src="/img/vector-334.svg" />
                  <img className="vector-331" alt="Vector" src="/img/vector-335.svg" />
                  <img className="vector-332" alt="Vector" src="/img/vector-336.svg" />
                  <img className="vector-333" alt="Vector" src="/img/vector-337.svg" />
                  <img className="vector-334" alt="Vector" src="/img/vector-338.svg" />
                  <img className="vector-335" alt="Vector" src="/img/vector-339.svg" />
                  <img className="vector-336" alt="Vector" src="/img/vector-340.svg" />
                  <img className="vector-110" alt="Vector" src="/img/vector-341.svg" />
                  <img className="vector-337" alt="Vector" src="/img/vector-342.svg" />
                  <img className="vector-338" alt="Vector" src="/img/vector-343.svg" />
                  <img className="vector-339" alt="Vector" src="/img/vector-344.svg" />
                  <img className="vector-340" alt="Vector" src="/img/vector-345.svg" />
                  <img className="vector-341" alt="Vector" src="/img/vector-346.svg" />
                  <img className="vector-118" alt="Vector" src="/img/vector-347.svg" />
                  <img className="vector-342" alt="Vector" src="/img/vector-348.svg" />
                  <img className="vector-119" alt="Vector" src="/img/vector-349.svg" />
                  <img className="vector-343" alt="Vector" src="/img/vector-350.svg" />
                  <img className="vector-120" alt="Vector" src="/img/vector-351.svg" />
                  <img className="vector-344" alt="Vector" src="/img/vector-352.svg" />
                  <img className="vector-345" alt="Vector" src="/img/vector-353.svg" />
                  <img className="vector-346" alt="Vector" src="/img/vector-354.svg" />
                  <img className="vector-347" alt="Vector" src="/img/vector-355.svg" />
                  <img className="vector-348" alt="Vector" src="/img/vector-356.svg" />
                  <img className="vector-349" alt="Vector" src="/img/vector-357.svg" />
                  <img className="vector-350" alt="Vector" src="/img/vector-358.svg" />
                  <img className="vector-351" alt="Vector" src="/img/vector-359.svg" />
                  <img className="vector-352" alt="Vector" src="/img/vector-360.svg" />
                  <img className="vector-353" alt="Vector" src="/img/vector-361.svg" />
                  <img className="vector-354" alt="Vector" src="/img/vector-362.svg" />
                  <img className="vector-355" alt="Vector" src="/img/vector-363.svg" />
                  <img className="vector-356" alt="Vector" src="/img/vector-364.svg" />
                  <img className="vector-357" alt="Vector" src="/img/vector-365.svg" />
                  <img className="vector-358" alt="Vector" src="/img/vector-366.svg" />
                  <img className="vector-359" alt="Vector" src="/img/vector-367.svg" />
                  <img className="vector-360" alt="Vector" src="/img/vector-368.svg" />
                  <img className="vector-361" alt="Vector" src="/img/vector-369.svg" />
                  <img className="vector-362" alt="Vector" src="/img/vector-370.svg" />
                  <img className="vector-363" alt="Vector" src="/img/vector-371.svg" />
                  <img className="vector-364" alt="Vector" src="/img/vector-372.svg" />
                  <img className="vector-365" alt="Vector" src="/img/vector-373.svg" />
                  <img className="vector-366" alt="Vector" src="/img/vector-374.svg" />
                  <img className="vector-367" alt="Vector" src="/img/vector-375.svg" />
                  <img className="vector-368" alt="Vector" src="/img/vector-376.svg" />
                  <img className="vector-369" alt="Vector" src="/img/vector-377.svg" />
                  <img className="vector-370" alt="Vector" src="/img/vector-378.svg" />
                  <img className="vector-150" alt="Vector" src="/img/vector-379.svg" />
                  <img className="vector-371" alt="Vector" src="/img/vector-380.svg" />
                  <img className="vector-372" alt="Vector" src="/img/vector-381.svg" />
                  <img className="vector-153" alt="Vector" src="/img/vector-382.svg" />
                  <img className="vector-373" alt="Vector" src="/img/vector-383.svg" />
                  <img className="vector-374" alt="Vector" src="/img/vector-384.svg" />
                  <img className="vector-375" alt="Vector" src="/img/vector-385.svg" />
                  <img className="vector-376" alt="Vector" src="/img/vector-386.svg" />
                  <img className="vector-377" alt="Vector" src="/img/vector-387.svg" />
                  <img className="vector-378" alt="Vector" src="/img/vector-388.svg" />
                  <img className="vector-161" alt="Vector" src="/img/vector-389.svg" />
                  <img className="vector-379" alt="Vector" src="/img/vector-390.svg" />
                  <img className="vector-160" alt="Vector" src="/img/vector-391.svg" />
                  <img className="vector-162" alt="Vector" src="/img/vector-392.svg" />
                  <img className="vector-380" alt="Vector" src="/img/vector-393.svg" />
                  <img className="vector-381" alt="Vector" src="/img/vector-394.svg" />
                  <img className="vector-165" alt="Vector" src="/img/vector-395.svg" />
                  <img className="vector-382" alt="Vector" src="/img/vector-396.svg" />
                  <img className="vector-383" alt="Vector" src="/img/vector-397.svg" />
                  <img className="vector-384" alt="Vector" src="/img/vector-398.svg" />
                  <img className="vector-170" alt="Vector" src="/img/vector-399.svg" />
                  <img className="vector-385" alt="Vector" src="/img/vector-400.svg" />
                  <img className="vector-386" alt="Vector" src="/img/vector-401.svg" />
                  <img className="vector-387" alt="Vector" src="/img/vector-402.svg" />
                  <img className="vector-172" alt="Vector" src="/img/vector-403.svg" />
                  <img className="vector-388" alt="Vector" src="/img/vector-404.svg" />
                  <img className="vector-173" alt="Vector" src="/img/vector-405.svg" />
                  <img className="vector-175" alt="Vector" src="/img/vector-406.svg" />
                  <img className="vector-389" alt="Vector" src="/img/vector-407.svg" />
                  <img className="vector-390" alt="Vector" src="/img/vector-408.svg" />
                  <img className="vector-391" alt="Vector" src="/img/vector-409.svg" />
                  <img className="vector-179" alt="Vector" src="/img/vector-410.svg" />
                  <img className="vector-392" alt="Vector" src="/img/vector-411.svg" />
                  <img className="vector-393" alt="Vector" src="/img/vector-412.svg" />
                  <img className="vector-394" alt="Vector" src="/img/vector-413.svg" />
                  <img className="vector-395" alt="Vector" src="/img/vector-414.svg" />
                  <img className="vector-396" alt="Vector" src="/img/vector-415.svg" />
                  <img className="vector-397" alt="Vector" src="/img/vector-416.svg" />
                  <img className="vector-398" alt="Vector" src="/img/vector-417.svg" />
                  <img className="vector-399" alt="Vector" src="/img/vector-418.svg" />
                  <img className="vector-195" alt="Vector" src="/img/vector-419.svg" />
                  <img className="vector-400" alt="Vector" src="/img/vector-420.svg" />
                  <img className="vector-401" alt="Vector" src="/img/vector-421.svg" />
                  <img className="vector-201" alt="Vector" src="/img/vector-422.svg" />
                  <img className="vector-191" alt="Vector" src="/img/vector-423.svg" />
                  <img className="vector-192" alt="Vector" src="/img/vector-424.svg" />
                  <img className="vector-194" alt="Vector" src="/img/vector-425.svg" />
                  <img className="vector-198" alt="Vector" src="/img/vector-426.svg" />
                  <img className="vector-199" alt="Vector" src="/img/vector-427.svg" />
                  <img className="vector-402" alt="Vector" src="/img/vector-428.svg" />
                  <img className="vector-403" alt="Vector" src="/img/vector-429.svg" />
                  <img className="vector-203" alt="Vector" src="/img/vector-430.svg" />
                  <img className="vector-404" alt="Vector" src="/img/vector-431.svg" />
                  <img className="vector-405" alt="Vector" src="/img/vector-432.svg" />
                  <img className="vector-406" alt="Vector" src="/img/vector-433.svg" />
                  <img className="vector-407" alt="Vector" src="/img/vector-434.svg" />
                  <img className="vector-408" alt="Vector" src="/img/vector-435.svg" />
                  <img className="vector-206" alt="Vector" src="/img/vector-436.svg" />
                  <img className="vector-409" alt="Vector" src="/img/vector-437.svg" />
                  <img className="vector-410" alt="Vector" src="/img/vector-438.svg" />
                  <img className="vector-411" alt="Vector" src="/img/vector-439.svg" />
                  <img className="vector-412" alt="Vector" src="/img/vector-440.svg" />
                  <img className="vector-214" alt="Vector" src="/img/vector-441.svg" />
                  <img className="vector-216" alt="Vector" src="/img/vector-442.svg" />
                  <img className="vector-413" alt="Vector" src="/img/vector-443.svg" />
                  <img className="vector-414" alt="Vector" src="/img/vector-444.svg" />
                  <img className="vector-415" alt="Vector" src="/img/vector-445.svg" />
                  <img className="vector-416" alt="Vector" src="/img/vector-446.svg" />
                  <img className="vector-417" alt="Vector" src="/img/vector-447.svg" />
                  <img className="vector-418" alt="Vector" src="/img/vector-448.svg" />
                  <img className="vector-419" alt="Vector" src="/img/vector-449.svg" />
                  <img className="vector-420" alt="Vector" src="/img/vector-450.svg" />
                  <img className="vector-421" alt="Vector" src="/img/vector-451.svg" />
                  <img className="vector-422" alt="Vector" src="/img/vector-452.svg" />
                  <img className="vector-423" alt="Vector" src="/img/vector-453.svg" />
                  <img className="vector-424" alt="Vector" src="/img/vector-454.svg" />
                  <img className="vector-425" alt="Vector" src="/img/vector-455.svg" />
                  <img className="vector-233" alt="Vector" src="/img/vector-456.svg" />
                  <img className="vector-426" alt="Vector" src="/img/vector-457.svg" />
                  <img className="vector-427" alt="Vector" src="/img/vector-458.svg" />
                  <img className="vector-428" alt="Vector" src="/img/vector-459.svg" />
                  <img className="vector-429" alt="Vector" src="/img/vector-460.svg" />
                  <img className="vector-243" alt="Vector" src="/img/vector-461.svg" />
                  <img className="vector-430" alt="Vector" src="/img/vector-462.svg" />
                  <img className="vector-246" alt="Vector" src="/img/vector-463.svg" />
                  <img className="vector-431" alt="Vector" src="/img/vector-464.svg" />
                  <img className="vector-249" alt="Vector" src="/img/vector-465.svg" />
                  <img className="vector-247" alt="Vector" src="/img/vector-466.svg" />
                  <img className="vector-432" alt="Vector" src="/img/vector-467.svg" />
                  <img className="vector-433" alt="Vector" src="/img/vector-468.svg" />
                  <img className="vector-252" alt="Vector" src="/img/vector-469.svg" />
                  <img className="vector-250" alt="Vector" src="/img/vector-470.svg" />
                  <img className="vector-434" alt="Vector" src="/img/vector-471.svg" />
                  <div className="group-4">
                    <div className="text-wrapper-7">$BUX</div>
                  </div>
                </div>
              </div>
              <p className="stake-to-earn-daily">{title}</p>
            </div>
        );

    }

export default SlideComponent2