import React from "react";

function Board_component2() {
    return (
      <div className="frame-29">
            <div className="div-2">
              <div className="element-sol-wrapper">
                <img
                  className="element-sol"
                  alt="Element sol"
                  src="/img/9297384-sol-blockchain-coins-cryptocurrency-crypto-icon-1-1.svg"
                />
              </div>
            </div>
            <div className="frame-30">
              <div className="frame-31">
                <div className="frame-32">
                  <p className="text-wrapper-17">DAO WALLET &amp; REV SHARE</p>
                  <p className="text-wrapper-18">
                    100% of revenue generated by the DAO is added to our community staking
                    <br />
                    wallet. That money belongs to to the holders of the $BUX token.
                  </p>
                </div>
              </div>
              <div className="frame-33">
                <div className="text-wrapper-19">CASHOUT $BUX TO $SOL</div>
              </div>
            </div>
          </div>
    );
}

export default Board_component2
